services:
  smaug:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
#    environment:
  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: powerdrive
      POSTGRES_USER: powerdrive
      POSTGRES_DB: powerdrive
    volumes:
      - ./db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "powerdrive"]
      interval: 10s
      timeout: 5s
      retries: 5