"""Init 2

Revision ID: 7ea9b7cc933b
Revises: caee35793f9c
Create Date: 2023-05-07 12:08:45.295648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ea9b7cc933b'
down_revision = 'caee35793f9c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pd_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('pd_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('path', sa.String(length=2500), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('is_root_dir', sa.Boolean(), nullable=True),
    sa.Column('is_dir', sa.Boolean(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['pd_user.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['pd_file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pd_group',
    sa.Column('group_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_name', sa.String(length=100), nullable=True),
    sa.Column('group_description', sa.String(length=100), nullable=True),
    sa.Column('group_owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_owner_id'], ['pd_user.id'], ),
    sa.PrimaryKeyConstraint('group_id'),
    sa.UniqueConstraint('group_name')
    )
    op.create_table('pd_group_user',
    sa.Column('group_user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['pd_group.group_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['pd_user.id'], ),
    sa.PrimaryKeyConstraint('group_user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pd_group_user')
    op.drop_table('pd_group')
    op.drop_table('pd_file')
    op.drop_table('pd_user')
    # ### end Alembic commands ###
